modLoader="javafml"
loaderVersion="[45,)"
license="All rights reserved"
issueTrackerURL="https://github.com/ricksouth/serilum-mc-mods/labels/Mod:%20Snowballs%20Freeze%20Mobs"
logoFile="icon.png"

[[mods]]
modId="snowballsfreezemobs"
version="3.1"
displayName="Snowballs Freeze Mobs"
displayURL="https://curseforge.com/minecraft/mc-mods/snowballs-freeze-mobs"
authors="Rick South"
description='''Hitting mobs with a snowball will result in them being frozen for a configurable amount of time.
If you would like to contribute too, check out https://ricksouth.com/donate. Appreciate it! <3   
'''
credits='''Thank you very much to my Membership sponsors for supporting the development of this mod:  

Adam E, Alister, aternosorg, Cherriesaurus, Greg Johnson, Kreezxil, Michael W. S., Mir3JonCZ, nbtc971, Rebecca Hb., Robert Gilbert, Shana Gitnick, Sija, silver Bowsman, Tyler Behl   

If you would like to contribute too, check out https://ricksouth.com/donate. Appreciate it! <3   
'''

[[dependencies.snowballsfreezemobs]]
    modId="collective"
    mandatory=true
    versionRange="[6.53,)"
    ordering="NONE"
    side="BOTH"